services:
  db:
    image: postgres:15-alpine
    container_name: boxin1_cloud_service_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: azerty
      POSTGRES_DB: boxin1
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d boxin1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - n8n-network  # Ajout au réseau n8n

  app:
    build: .
    container_name: boxin1_cloud_service_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - n8n-network  # Ajout au réseau n8n
    
volumes:
  pgdata:

networks:
  n8n-network:
    external: true  # Utilise le réseau existant de n8n
    name: n8n_n8n-network  # Nom exact du réseau créé par n8n